const nflTeamIds = [
  ["arizona-cardinals", "Arizona Cardinals"],
  ["atlanta-falcons", "Atlanta Falcons"],
  ["baltimore-ravens", "Baltimore Ravens"],
  ["buffalo-bills", "Buffalo Bills"],
  ["carolina-panthers", "Carolina Panthers"],
  ["chicago-bears", "Chicago Bears"],
  ["cincinnati-bengals", "Cincinnati Bengals"],
  ["cleveland-browns", "Cleveland Browns"],
  ["dallas-cowboys", "Dallas Cowboys"],
  ["denver-broncos", "Denver Broncos"],
  ["detroit-lions", "Detroit Lions"],
  ["green-bay-packers", "Green Bay Packers"],
  ["houston-texans", "Houston Texans"],
  ["indianapolis-colts", "Indianapolis Colts"],
  ["jacksonville-jaguars", "Jacksonville Jaguars"],
  ["kansas-city-chiefs", "Kansas City Chiefs"],
  ["oakland-raiders", "Las Vegas Raiders"],
  ["los-angeles-chargers", "Los Angeles Chargers"],
  ["los-angeles-rams", "Los Angeles Rams"],
  ["miami-dolphins", "Miami Dolphins"],
  ["minnesota-vikings", "Minnesota Vikings"],
  ["new-england-patriots", "New England Patriots"],
  ["new-orleans-saints", "New Orleans Saints"],
  ["new-york-giants", "New York Giants"],
  ["new-york-jets", "New York Jets"],
  ["philadelphia-eagles", "Philadelphia Eagles"],
  ["pittsburgh-steelers", "Pittsburgh Steelers"],
  ["san-francisco-49ers", "San Francisco 49ers"],
  ["seattle-seahawks", "Seattle Seahawks"],
  ["tampa-bay-buccaneers", "Tampa Bay Buccaneers"],
  ["tennessee-titans", "Tennessee Titans"],
  ["washington-redskins", "Washington Football Team"],
];

const nbaTeamIds = [
  ["atlanta-hawks", "Atlanta Hawks"],
  ["boston-celtics", "Boston Celtics"],
  ["brooklyn-nets", "Brooklyn Nets"],
  ["charlotte-hornets", "Charlotte Hornets"],
  ["chicago-bulls", "Chicago Bulls"],
  ["cleveland-cavaliers", "Cleveland Cavaliers"],
  ["dallas-mavericks", "Dallas Mavericks"],
  ["denver-nuggets", "Denver Nuggets"],
  ["detroit-pistons", "Detroit Pistons"],
  ["golden-state-warriors", "Golden State Warriors"],
  ["houston-rockets", "Houston Rockets"],
  ["indiana-pacers", "Indiana Pacers"],
  ["la-clippers", "Los Angeles Clippers"],
  ["los-angeles-lakers", "Los Angeles Lakers"],
  ["memphis-grizzlies", "Memphis Grizzlies"],
  ["miami-heat", "Miami Heat"],
  ["milwaukee-bucks", "Milwaukee Bucks"],
  ["minnesota-timberwolves", "Minnesota Timberwolves"],
  ["new-orleans-pelicans", "New Orleans Pelicans"],
  ["new-york-knicks", "New York Knicks"],
  ["oklahoma-city-thunder", "Oklahoma City Thunder"],
  ["orlando-magic", "Orlando Magic"],
  ["philadelphia-76ers", "Philadelphia 76ers"],
  ["phoenix-suns", "Phoenix Suns"],
  ["portland-trail-blazers", "Portland Trail Blazers"],
  ["sacramento-kings", "Sacramento Kings"],
  ["san-antonio-spurs", "San Antonio Spurs"],
  ["toronto-raptors", "Toronto Raptors"],
  ["utah-jazz", "Utah Jazz"],
  ["washington-wizards", "Washington Wizards"],
];

const nhlTeamIds = [
  ["anaheim-ducks", "Anaheim Ducks"],
  ["arizona-coyotes", "Arizona Coyotes"],
  ["boston-bruins", "Boston Bruins"],
  ["buffalo-sabres", "Buffalo Sabres"],
  ["calgary-flames", "Calgary Flames"],
  ["carolina-hurricanes", "Carolina Hurricanes"],
  ["chicago-blackhawks", "Chicago Blackhawks"],
  ["colorado-avalanche", "Colorado Avalanche"],
  ["columbus-blue-jackets", "Columbus Blue Jackets"],
  ["dallas-stars", "Dallas Stars"],
  ["detroit-red-wings", "Detroit Red Wings"],
  ["edmonton-oilers", "Edmonton Oilers"],
  ["florida-panthers", "Florida Panthers"],
  ["los-angeles-kings", "Los Angeles Kings"],
  ["minnesota-wild", "Minnesota Wild"],
  ["montreal-canadiens", "Montreal Canadiens"],
  ["nashville-predators", "Nashville Predators"],
  ["new-jersey-devils", "New Jersey Devils"],
  ["new-york-islanders", "New York Islanders"],
  ["new-york-rangers", "New York Rangers"],
  ["ottawa-senators", "Ottawa Senators"],
  ["philadelphia-flyers", "Philadelphia Flyers"],
  ["pittsburgh-penguins", "Pittsburgh Penguins"],
  ["san-jose-sharks", "San Jose Sharks"],
  ["seattle-kraken", "Seattle Kraken"],
  ["st-louis-blues", "St Louis Blues"],
  ["tampa-bay-lightning", "Tampa Bay Lightning"],
  ["toronto-maple-leafs", "Toronto Maple Leafs"],
  ["vancouver-canucks", "Vancouver Canucks"],
  ["vegas-golden-knights", "Vegas Golden Knights"],
  ["washington-capitals", "Washington Capitals"],
  ["winnipeg-jets", "Winnipeg Jets"],
];

const mlbTeamIds = [
  ["arizona-diamondbacks", "Arizona Diamondbacks"],
  ["atlanta-braves", "Atlanta Braves"],
  ["baltimore-orioles", "Baltimore Orioles"],
  ["boston-red-sox", "Boston Red Sox"],
  ["chicago-white-sox", "Chicago White Sox"],
  ["chicago-cubs", "Chicago Cubs"],
  ["cincinnati-reds", "Cincinnati Reds"],
  ["cleveland-indians", "Cleveland Indians"],
  ["colorado-rockies", "Colorado Rockies"],
  ["detroit-tigers", "Detroit Tigers"],
  ["houston-astros", "Houston Astros"],
  ["kansas-city-royals", "Kansas City Royals"],
  ["los-angeles-angels", "Los Angeles Angels"],
  ["los-angeles-dodgers", "Los Angeles Dodgers"],
  ["miami-marlins", "Miami Marlins"],
  ["milwaukee-brewers", "Milwaukee Brewers"],
  ["minnesota-twins", "Minnesota Twins"],
  ["new-york-yankees", "New York Yankees"],
  ["new-york-mets", "New York Mets"],
  ["oakland-athletics", "Oakland Athletics"],
  ["philadelphia-phillies", "Philadelphia Phillies"],
  ["pittsburgh-pirates", "Pittsburgh Pirates"],
  ["san-diego-padres", "San Diego Padres"],
  ["san-francisco-giants", "San Francisco Giants"],
  ["seattle-mariners", "Seattle Mariners"],
  ["st-louis-cardinals", "St. Louis Cardinals"],
  ["tampa-bay-rays", "Tampa Bay Rays"],
  ["texas-rangers", "Texas Rangers"],
  ["toronto-blue-jays", "Toronto Blue Jays"],
  ["washington-nationals", "Washington Nationals"],
];

export { nflTeamIds, nbaTeamIds, nhlTeamIds, mlbTeamIds };
